<?php
    $pixInfo = $this->getPixInfo();
    if (!empty($pixInfo) && $this->getInfo()->getOrder()->getStatus() == 'pending'):
?>
    <span><?php echo __($this->getTitle()) ?></span>
    <hr />
    <div style="text-align: center">
        <img width="130" style="margin-bottom: 10px" alt="Pix"
             src="<?= $escaper->escapeUrl($block->getViewFileUrl('PlugHacker_PlugPagamentos::images/pix.png')) ?>">
        <br>
        <img width="130" style="margin-bottom: 10px" src="<?= $pixInfo['qrCodeImageUrl']?>" />
        <span style="word-wrap: break-word;"><?= $pixInfo['qrCodeData']?></span>
    </div>
<?php else: ?>
	<span><?php echo __($this->getTitle()) ?></span>
    <br />
    <img width="130" style="margin-bottom: 10px" alt="Pix"
         src="<?= $escaper->escapeUrl($block->getViewFileUrl('PlugHacker_PlugPagamentos::images/pix.png')) ?>">
<?php endif ?>
