<?php
    $pixInfo = $this->getPixInfo();
    if (!empty($pixInfo) && $this->getInfo()->getOrder()->getStatus() == 'pending'):
?>
    <span><?php echo __($this->getTitle()) ?></span>
    <hr />
    <div style="text-align: center">
        <img width="130" style="margin-bottom: 10px" src="https://staging-cdn.plug.com/assets/images/site/illustrations/pix-bc-logo-2.png" />
        <img width="130" style="margin-bottom: 10px" src="<?= $pixInfo['qrCodeImageUrl']?>" />
        <span style="word-wrap: break-word;"><?= $pixInfo['qrCodeData']?></span>
    </div>
<?php else: ?>
	<span><?php echo __($this->getTitle()) ?></span>
    <br />
    <img width="130" style="margin-bottom: 10px" src="https://staging-cdn.plug.com/assets/images/site/illustrations/pix-bc-logo-2.png" />
<?php endif ?>
